substitutions:
  _REGION: "us-central1"
  _ZONE: "us-central1-a"

steps:
  # Step 1: Create a unique standard GCS bucket for the test run.
  - name: "gcr.io/cloud-builders/gcloud"
    id: "create-standard-bucket"
    args:
      - "storage"
      - "buckets"
      - "create"
      - "gs://gcsfs-test-standard-${SHORT_SHA}"
      - "--project=${PROJECT_ID}"
      - "--location=${_REGION}"
    waitFor: ["-"]

  # Step 2: Create a unique HNS-enabled GCS bucket for the test run.
  - name: "gcr.io/cloud-builders/gcloud"
    id: "create-hns-bucket"
    args:
      - "storage"
      - "buckets"
      - "create"
      - "gs://gcsfs-test-hns-${SHORT_SHA}"
      - "--project=${PROJECT_ID}"
      - "--location=${_REGION}"
      - "--enable-hierarchical-namespace"
      - "--uniform-bucket-level-access"
    waitFor: ["-"]

  # Step 3: Create a GCE VM to run the tests.
  # The VM is created in the same zone as the buckets to test zonal bucket features.
  # It's given the 'cloud-platform' scope to allow it to access GCS and other services.
  - name: "gcr.io/cloud-builders/gcloud"
    id: "create-vm"
    args:
      - "compute"
      - "instances"
      - "create"
      - "gcsfs-test-vm-${SHORT_SHA}"
      - "--project=${PROJECT_ID}"
      - "--zone=${_ZONE}"
      - "--machine-type=e2-medium"
      - "--image-family=debian-11"
      - "--image-project=debian-cloud"
      - "--scopes=https://www.googleapis.com/auth/cloud-platform" # Full access to project APIs
    waitFor: ["-"]

  # Step 4: Run the integration tests inside the newly created VM.
  # This step uses 'gcloud compute ssh' to execute a remote script.
  - name: "gcr.io/cloud-builders/gcloud"
    id: "run-tests-on-vm"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        # Wait for the VM to be fully initialized and SSH to be ready.
        for i in {1..10}; do
          if gcloud compute ssh gcsfs-test-vm-${SHORT_SHA} --zone=${_ZONE} --command="echo VM is ready"; then
            break
          fi
          echo "Waiting for VM to become available... (attempt $$i/10)"
          sleep 15
        done

        # Define the script to be executed on the VM.
        # This script installs dependencies, sets environment variables, and runs pytest.
        VM_SCRIPT="
          set -e
          echo '--- Installing git and cloning repository on VM ---'
          sudo apt-get update
          sudo apt-get install -y git python3-pip python3-venv

          # Clone the repository and checkout the specific commit from the build trigger.
          git clone https://github.com/fsspec/gcsfs.git
          cd gcsfs
          git checkout ${COMMIT_SHA}


          echo '--- Installing Python and dependencies on VM ---'
          python3 -m venv env
          source env/bin/activate

          pip install --upgrade pip
          # Install testing libraries explicitly, as they are not in setup.py
          pip install pytest pytest-timeout pytest-asyncio
          pip install -e .

          echo '--- Preparing test environment on VM ---'
          export GCSFS_TEST_BUCKET='gcsfs-test-standard-${SHORT_SHA}'
          export GCSFS_HNS_TEST_BUCKET='gcsfs-test-hns-${SHORT_SHA}'

          echo 'Standard Bucket: $$GCSFS_TEST_BUCKET'
          echo 'HNS Bucket: $$GCSFS_HNS_TEST_BUCKET'

          echo '--- Running pytest on VM ---'
          pytest -v gcsfs/tests/
        "

        # Execute the script on the VM via SSH.
        gcloud compute ssh gcsfs-test-vm-${SHORT_SHA} --zone=${_ZONE} --command="$$VM_SCRIPT"
    waitFor:
      - "create-vm"
      - "create-standard-bucket"
      - "create-hns-bucket"

  # --- Cleanup Steps ---
  # These steps will run after the test step, regardless of its success or failure,
  # to ensure resources are not left orphaned.

  # Step 5: Delete the GCE VM.
  - name: "gcr.io/cloud-builders/gcloud"
    id: "delete-vm"
    args:
      - "compute"
      - "instances"
      - "delete"
      - "gcsfs-test-vm-${SHORT_SHA}"
      - "--zone=${_ZONE}"
      - "--quiet"
    waitFor:
      - "run-tests-on-vm"

  # Step 6: Delete the standard GCS bucket.
  - name: "gcr.io/cloud-builders/gcloud"
    id: "delete-standard-bucket"
    args:
      ["storage", "rm", "--recursive", "gs://gcsfs-test-standard-${SHORT_SHA}"]
    waitFor:
      - "run-tests-on-vm"

  # Step 7: Delete the HNS GCS bucket.
  - name: "gcr.io/cloud-builders/gcloud"
    id: "delete-hns-bucket"
    args: ["storage", "rm", "--recursive", "gs://gcsfs-test-hns-${SHORT_SHA}"]
    waitFor:
      - "run-tests-on-vm"

timeout: "1800s" # 30 minutes

options:
  logging: CLOUD_LOGGING_ONLY
